defaults:
  - data_module: base_seq_cls
  - task: predict
  - trainer: default
  - _self_

seed:
  seed_value: 1234

label_columns:
  - _target_: bmfm_targets.config.LabelColumnInfo
    label_column_name: "Condition"
    is_regression_label: false
    n_unique_values: 2
    decode_from: 2
  - _target_: bmfm_targets.config.LabelColumnInfo
    label_column_name: "celltypes"
    is_regression_label: false
    n_unique_values: 5
    decode_from: 1
  - _target_: bmfm_targets.config.LabelColumnInfo
    label_column_name: "sample"
    is_regression_label: false
    n_unique_values: 58
    decode_from: 4
  - _target_: bmfm_targets.config.LabelColumnInfo
    label_column_name: "sample_from_Condition"
    is_regression_label: false
    n_unique_values: 58
    decode_from: 2
    gradient_reversal_coefficient: "${gradient_reversal_coefficient}"
  - _target_: bmfm_targets.config.LabelColumnInfo
    label_column_name: "Gender"
    is_regression_label: false
    n_unique_values: 2
    decode_from: 3


data_module:
  max_length: "${max_length}"
  dataset_kwargs:
    processed_data_source: ${input_file}
    label_dict_path: /sci/backup/dandanbz/haya.benhayon/IBM/biomed-multi-omic/label_dict_subs.json
  limit_genes: protein_coding #could be null, protein_coding, or tokenizer
  transform_datasets: false
  collation_strategy: multitask
  log_normalize_transform: true


track_clearml:
  project_name: "predict"
  task_name: ${file_name}
  continue_last_task: False

task:
  checkpoint: ${checkpoint}
  output_embeddings: true
  output_predictions: true
  default_root_dir: ${working_dir}
  callbacks:
   - _target_: bmfm_targets.training.callbacks.BatchIntegrationCallback
     batch_column_name: ${batch_column_name}
     counts_column_name: ${counts_column_name}
trainer:
  learning_rate: 1.0e-5
  metrics:
   - name: accuracy
   - name: f1
   - name: precision
   - name: recall
  losses:
   - label_column_name: "Condition"
     name: cross_entropy # focal also supported, or mse if column is a regression_label
     weight: 2
   - label_column_name: "sample_from_Condition"
     name: cross_entropy # focal also supported, or mse if column is a regression_label
     weight: 1
   - label_column_name: "celltypes"
     name: cross_entropy
     weight: 2
   - label_column_name: "sample"
     name: cross_entropy
     weight: 1
   - label_column_name: "Gender"
     name: cross_entropy
     weight: 2
   - field_name: expressions
     name: mse
     ignore_zero: true
   - field_name: expressions
     name: is_zero_bce
  batch_prediction_behavior: track
  pooling_method: 2

accelerator: gpu
file_name: delete
max_length: 2048
gradient_reversal_coefficient: 1.5
input_file: /sci/backup/dandanbz/haya.benhayon/IBM/Seurat/Alpha_T1D_healthy/binned_vs_continues/run4_alpha_cells_RNA_metadata_codinggenes.h5ad
working_dir: /sci/backup/dandanbz/haya.benhayon/IBM/predict_biomed/test_4_9/
checkpoint: /sci/backup/dandanbz/haya.benhayon/IBM/finetune_bimed/CLS_tokens/finetune_ACTsW2_condW2_SW1_CLS_24_11/copy_epoch10_24_11/last.ckpt
target_column_name: Condition
batch_column_name: sample
counts_column_name: nFeature_RNA
pooling_method: 2